apiVersion: v1
kind: Secret
metadata:
  name: kcl-app-secrets
  namespace: kcl-app
type: Opaque
data:
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  MINIO_ROOT_USER: bWluaW9hZG1pbg==
  MINIO_ROOT_PASSWORD: bWluaW9wYXNzd29yZA==
  RABBITMQ_DEFAULT_USER: Z3Vlc3Q=
  RABBITMQ_DEFAULT_PASS: Z3Vlc3Q=
  AWS_ACCESS_KEY_ID: eW91cl9hY2Nlc3Nfa2V5
  AWS_SECRET_ACCESS_KEY: eW91cl9zZWNyZXRfa2V5
  AWS_SESSION_TOKEN: ''
